#!/bin/bash

java $SBT_OPTS -DsocksProxyHost=10.7.211.16 -DsocksProxyPort=1080 -Dfile.encoding=UTF-8 -Xss4M -Xmx1024M -XX:MaxPermSize=256M -XX:NewSize=128M -XX:NewRatio=3 -jar `dirname $0`/sbt-launch.jar "$@"
